site_name: fastrf
site_description: FastRF application, create link budgets, track compliance, fast to use, ready for use
site_url: https://github.com/iancleary/fastrf

theme:
    name: 'material'

repo_name: iancleary/fastrf
repo_url: https://github.com/iancleary/fastrf
edit_uri: ''

nav:
    - fastrf: 'index.md'
